Lockheed Inanimation: FaceTracker Class Reference
FaceTracker Class Reference
Tracks a face as it moves around.
#include <facetracker.h>
Public Member Functions
FaceTracker ()
Default constructor uses device 0.
FaceTracker (int deviceID)
Constructor uses specified device ID for VideoCapture.
void ClearAdditionalFlag (unsigned int flag)
Clears the passed flag from the additional flags.
unsigned int GetAdditionalFlags ()
Getter for flags used for cv::CascadeClassifier::detectMultiScale() These flags are appended to the flags already used for the function call. For example, FaceTracker::GetBestFacePosition will use.
QList< QRect > GetAllFacesPositions (bool normalized=false)
Returns a list of bounding rectangles of all of the faces.
QRect GetBestFacePosition (bool normalized=false)
Returns the bounding rectangle of the face with the highest confidence factor If there are multiple faces, only the bounding rectangle of the face with the highest confidence is returned.
QImage * GetFaceImage ()
Returns the cropped image of the tracked face If there is currently a face being tracked, the face is cropped out of the last processed frame.
QRect GetFacePosition (bool normalized=false)
Returns the rectangle of the currently tracked face.
QImage * GetLastImage ()
Returns the last processed frame The tracker internally saves the last processed frame and this function can be used to retrieve it. Along with the face positions, this can help display real time face tracking information.
QRect GetLastPosition (bool normalized=false)
Returns the last known position of the user.
int GetMinFeatureSize ()
Getter for minimum feature size used for cv::CascadeClassifier::detectMultiScale()
int GetMinNeighbors ()
Getter for minimum neighbors cutoff used for cv::CascadeClassifier::detectMultiScale()
float GetSearchScaleFactor ()
Getter for search scale factor used for cv::CascadeClassifier::detectMultiScale()
void ResetTracker ()
Stops tracking of the current face.
QRect SelectFace2Track (std::vector< cv::Rect > faceRects)
Selects which face to track from a list Given a list of bounding rectangles, this function select which face will be tracked from here on out.
void SetAdditionalFlag (unsigned int flag)
Adds flag to the set of additional flags.
void SetAdditionalFlags (unsigned int flags)
Sets the additional flags to flags.
void SetMinFeatureSize (int minFeatureSize)
Setter for minimum feature size used for cv::CascadeClassifier::detectMultiScale()
void SetMinNeighbors (int minNeighbors)
Setter for minimum neighbors cutoff used for cv::CascadeClassifier::detectMultiScale()
void SetProcessingImageDimensions (int width, int height)
Sets the dimensions for the image to be processed by OpenCV This option may effect performance and reliability of the face detection algorithms of OpenCV.
void SetSearchScaleFactor (float searchScaleFactor)
Setter for search scale factor used for cv::CascadeClassifier::detectMultiScale()
Private Member Functions
QRect findClosest (const std::vector< cv::Rect > &rects, QPoint point)
Finds rectangle with center closest to point.
void GetProcessReadyWebcamImage (cv::Mat &cameraFrame)
Obtains a properly sized and processed image for CascadeClassifer The obtained image is sized down, converted to gray, and undergone histogram equalization. These alterations are aimed at improving performance and detection accuracy.
void Init (int deviceID)
Initialization function.
void LoadCascadeClassifier (const std::string filename)
CascadeClassifier is loaded with the file.
Private Attributes
unsigned int m_additionalFlags
Additional flags passed to cv::CascadeClassifier::detectMultiScale()
cv::Mat m_cameraFrame
Stores the last processed frame (needed for face extraction)
std::string m_classifierXmlFilename
The filename of the XML containing the classifier data.
cv::CascadeClassifier m_faceDetector
Used for face detection.
unsigned int m_imageHeight
Specifies the height of the image on which face detection is performed.
unsigned int m_imageWidth
Specifies the width of the image on which face detection is performed.
QRect m_lastPosition
Stores the last bounding rectangle of the tracked face.
cv::Size m_minFeatureSize
Minimum feature size used for cv::CascadeClassifier::detectMultiScale()
int m_minNeighbors
Minimum number of Neighbors to be classified as a face.
float m_searchScaleFactor
Search scale factor used for cv::CascadeClassifier::detectMultiScale()
cv::VideoCapture m_vc
Used for acquiring images from camera.
Static Private Attributes
static const QRect InvalidQRect
Easy way to create an InvalidRect.
Detailed Description
Tracks a face as it moves around.
This class is a wrapper around OpenCV and provides an eassy to use interface for tracking a face between frames. The class exposes several face detection tuning parameters. FaceTracker uses OpenCV to track a moving face using a webcam. The device ID of the webcam to use can be specified in the constructor of the class otherwise the first webcam (device ID: 0) is used.
In the presence of multiple faces, FaceTracker will attempt to track the same face as it moves around the scree. If multiple faces are present a face is selected to be tracked as per the FaceTracker::SelectFace2Track.
See Also
FaceTracker::SelectFace2Track
The class also exposes some parameters for tuning the face detection:
See Also
FaceTracker::m_minFeatureSize
FaceTracker::m_searchScaleFactor
FaceTracker::m_minNeighbors
FaceTracker::m_additionalFlags
Typical Use Case
Typically this class will be used in a tight loop with repeated calls to one of the face position acquisition functions such as FaceTracker::GetFacePosition, FaceTracker::GetAllFacesPositions, FaceTracker::GetFacePosition. The less time there is between function calls, the more reliable the face tracking will be, especially in the case of multiple faces on the screen.
while(1)
{
      QRect rect = faceTracker.GetFacePosition();
      QImage *image = faceTracker.GetLastImage();
      QPainter p;
      p.begin(image);
      p.setPen(QPen(Qt::red));
      p.drawRect(rect);
      p.end();
      // Display anotated image on screen...
}
Definition at line 84 of file facetracker.h.
Constructor & Destructor Documentation
FaceTracker::FaceTracker (int deviceID)
Constructor uses specified device ID for VideoCapture.
Parameters
deviceID device to be used for VideoCapture and image acquisition
Definition at line 19 of file facetracker.cpp.
References Init().
Member Function Documentation
void FaceTracker::ClearAdditionalFlag (unsigned int flag)
Clears the passed flag from the additional flags.
m_additionalFlags = m_additionalFlags & (~flag);
Parameters
flag Flag to be cleared
Definition at line 191 of file facetracker.cpp.
References m_additionalFlags.
QRect FaceTracker::findClosest (const std::vector< cv::Rect > & rects, QPoint point) private
Finds rectangle with center closest to point.
Parameters
rects List of rectangles
point Target point
Definition at line 278 of file facetracker.cpp.
unsigned int FaceTracker::GetAdditionalFlags ()
Getter for flags used for cv::CascadeClassifier::detectMultiScale() These flags are appended to the flags already used for the function call. For example, FaceTracker::GetBestFacePosition will use.
CASCADE_FIND_BIGGEST_OBJECT | CASCADE_DO_ROUGH_SEARCH | m_additionalFlags
for the flags parameter of the cv::CascadeClassifier::detectMultiScale() function call
Definition at line 181 of file facetracker.cpp.
References m_additionalFlags.
QList< QRect > FaceTracker::GetAllFacesPositions (bool normalized = false)
Returns a list of bounding rectangles of all of the faces.
 Bounding rectangles of all faces currently in view are returned.
Parameters
normalized See Normalized Rectangles
Returns
List of bounding rectangles of all faces
Note
No confidence information is supplied with each face, but all detected faces meet the FaceTracker::minNeighbors factor.
After this function is called, the FaceTracker::GetFaceImage will not return a usable result.
Definition at line 76 of file facetracker.cpp.
References GetProcessReadyWebcamImage(), m_additionalFlags, m_faceDetector, m_imageHeight, m_imageWidth, m_minNeighbors, and m_searchScaleFactor.
QRect FaceTracker::GetBestFacePosition (bool normalized = false)
Returns the bounding rectangle of the face with the highest confidence factor If there are multiple faces, only the bounding rectangle of the face with the highest confidence is returned.
Parameters
normalized See Normalized Rectangles
Returns
Bounding rectangle of face with highest confidence factor
Definition at line 108 of file facetracker.cpp.
References GetProcessReadyWebcamImage(), InvalidQRect, m_additionalFlags, m_faceDetector, m_imageHeight, m_imageWidth, m_lastPosition, m_minNeighbors, and m_searchScaleFactor.
QImage * FaceTracker::GetFaceImage ()
Returns the cropped image of the tracked face If there is currently a face being tracked, the face is cropped out of the last processed frame.
Returns
Cropped image of the tracked face. NULL is returned if no face was detected in the last processed frame.
Todo:
This is very expensive and inefficient way of performing this action
Definition at line 210 of file facetracker.cpp.
References GetLastImage(), and m_lastPosition.
QRect FaceTracker::GetFacePosition (bool normalized = false)
Returns the rectangle of the currently tracked face.
 If there is no face currently being tracked, or this function is called
 after a call to FaceTracker::ResetTracker, a new face will be selected as
 per FaceTracker::SelectFace2Track.
Parameters
normalized See Normalized Rectangles
Returns
Bounding rectangle of the face
Definition at line 30 of file facetracker.cpp.
References findClosest(), GetProcessReadyWebcamImage(), InvalidQRect, m_additionalFlags, m_faceDetector, m_imageHeight, m_imageWidth, m_lastPosition, m_minFeatureSize, m_minNeighbors, m_searchScaleFactor, and SelectFace2Track().
QImage * FaceTracker::GetLastImage ()
Returns the last processed frame The tracker internally saves the last processed frame and this function can be used to retrieve it. Along with the face positions, this can help display real time face tracking information.
Returns
Last Processed frame
Todo:
This will corrupt image if function called multiple times, or FaceTracker::GetFaceImage gets called
Definition at line 201 of file facetracker.cpp.
References m_cameraFrame.
QRect FaceTracker::GetLastPosition (bool normalized = false)
Returns the last known position of the user.
This function does not acquire a new image and run face recognition on it. Simply returns the last location.
Definition at line 219 of file facetracker.cpp.
References m_imageHeight, m_imageWidth, and m_lastPosition.
void FaceTracker::GetProcessReadyWebcamImage (cv::Mat & cameraFrame) private
Obtains a properly sized and processed image for CascadeClassifer The obtained image is sized down, converted to gray, and undergone histogram equalization. These alterations are aimed at improving performance and detection accuracy.
Parameters
cameraFrame [out] The captured image is stored
Note
This function alters the last saved camera frame.
Definition at line 300 of file facetracker.cpp.
References m_cameraFrame, and m_vc.
void FaceTracker::Init (int deviceID) private
Initialization function.
 Performs the initialization of the class, should only be called
 from constructors
Parameters
deviceID Device to be used for VideoCapture and image acquisition
Definition at line 233 of file facetracker.cpp.
References DEFAULT_ADDITIONAL_FLAGS, DEFAULT_CLASSIFIER_XML_FILENAME, DEFAULT_IMAGE_HEIGHT, DEFAULT_IMAGE_WIDTH, DEFAULT_MIN_FEATURE_SIZE, DEFAULT_MIN_NEIGHBORS_CUTOFF, DEFAULT_SEARCH_SCALE_FACTOR, LoadCascadeClassifier(), m_additionalFlags, m_classifierXmlFilename, m_minFeatureSize, m_minNeighbors, m_searchScaleFactor, m_vc, and SetProcessingImageDimensions().
void FaceTracker::LoadCascadeClassifier (const std::string filename) private
CascadeClassifier is loaded with the file.
Parameters
filename Full or relative path of the file
Definition at line 266 of file facetracker.cpp.
References m_faceDetector.
void FaceTracker::ResetTracker ()
Stops tracking of the current face.
This Tracker will attempt to follow the same face around as it moves around the field of view of the camera. This function stops the tracking of the current face, the next time position information is requested, a new face will be selected to be tracked.
Definition at line 24 of file facetracker.cpp.
References m_lastPosition.
QRect FaceTracker::SelectFace2Track (std::vector< cv::Rect > faceRects)
Selects which face to track from a list Given a list of bounding rectangles, this function select which face will be tracked from here on out.
Parameters
faceRects list of faces to select from
Returns
Bounding rectangle of selected face
Definition at line 136 of file facetracker.cpp.
References findClosest(), m_imageHeight, and m_imageWidth.
void FaceTracker::SetAdditionalFlag (unsigned int flag)
Adds flag to the set of additional flags.
m_additionalFlags = m_additionalFlags | flag;
Parameters
flag Flag to be added to the set of additional flags
Definition at line 186 of file facetracker.cpp.
References m_additionalFlags.
void FaceTracker::SetAdditionalFlags (unsigned int flags)
Sets the additional flags to flags.
m_additionalFlags = flags
Parameters
flags The new additional flags
Warning
Currently set additional flags are lost!
Definition at line 196 of file facetracker.cpp.
References m_additionalFlags.
The documentation for this class was generated from the following files:
src/facetracker.h
src/facetracker.cpp