Lockheed Inanimation: FaceInvadersScene Class Reference
FaceInvadersScene Class Reference
Manages game logic and graphical scene. This object is responsible for managing all of the players and invaders on the graphical scene, as well as drawing the background. The graphical scene is used This object emits signals to notify of game state changes.
#include <faceinvaderswidget.h>
Public Types
enum GameState { Playing, Paused, Stopped, InitState }
Public Slots
void alienEvaded (int points)
Invader has died, award points to player.
void beginGame ()
Transitions the game tion playing state.
void createNewInvaders ()
Creates random number of Invaders, positioned randomly throughout the game screen.
void decreaseInvaderSpeed ()
Decrease the falling velocity of invaders.
void endGame ()
Transitions the game into stopped state.
void increaseInvaderSpeed ()
Increase the falling velocity of invaders.
void pauseGame ()
Transitions the game into paused state.
void resetGame ()
Transitions the game into initial state.
void setInvaderSpeed (qreal speed)
Set invader speed to specific value.
void updatePlayerPosition (QPoint position)
Updates the position of the player (only x-position!)
Signals
void gameOver (int m_scoreItem)
Idicates game state transition to game over
void gamePaused ()
Indiccates game state transition from playing to paused
void gameStarted (bool resumed)
Indicates game state transition from stopped to playing
Public Member Functions
FaceInvadersScene (QWidget *parent=0)
Default constructor.
~FaceInvadersScene ()
Destructor.
int getGameScore () const
Returns the score of the game.
QRectF getGameScreenSize ()
Returns rectangle of the game space.
qreal getInvaderDeathLine ()
Sets the line past which all invaders are destroyed.
GameState getState () const
Returns the current state of the game.
void setGameScreenSize (QRectF &rect)
Sets the rectangle for the game space.
Static Public Attributes
static const QRect DefaultGameSize = QRect(0,0, 600, 440)
Protected Member Functions
void drawBackground (QPainter *painter, const QRectF &rect)
Draws background for the game.
Private Member Functions
void updateScorePosition ()
Makes sure the score is always visible and does not run off the viewable area.
Private Attributes
QImage * background
Image to be painted as the background.
QTimer * m_advanceTimer
Timer for controlling Invader descent.
int m_gameScore
Maintains the game score.
QRectF m_gameSize
The size of the graphics scene, larger values result in more detailed graphics and smaller invaders.
GameState m_gameState
1 - Game running, 0 - Game not running
qreal m_invaderScale
The scaling of the invaders, <1 -> smaller, >1 -> larger, 1 -> unscaled.
qreal m_invaderSpeed
Invader speed parameter.
QPointF m_playerStartingPosition
The starting position of player, Y-coordinate is maintained throughout game play.
QGraphicsSimpleTextItem * m_scoreItem
Displays game score.
PlayerItem * player
PlayerItem for easy access.
Detailed Description
Manages game logic and graphical scene. This object is responsible for managing all of the players and invaders on the graphical scene, as well as drawing the background. The graphical scene is used This object emits signals to notify of game state changes.
The game can be paused, resumed, ended, and reset.
See Also
FaceInvadersScene::pauseGame()
FaceInvadersScene::beginGame()
FaceInvadersScene::endGame()
FaceInvadersScene::resetGame()
Game State Transitioning To transition between, what is normally thought of "Paused", "Stopped", and "Playing" states, the class provides several functions. FaceInvadersScene::beginGame() can be used to go into "Playing" mode without changing the current state of the scene. This allows flexibility for setting up the scene as desired and beginning the game from there. This function makes the existance of a "resume()" function unnecessary. FaceInvadersScene::resetGame() resets the scene state to an clear state having no Invaders, and a 0 score. FaceInvadersScene::endGame() forces the game to stop and display a game end message, whereas FaceInvadersScene::pauseGame() stops the game and displays a paused game message.
Definition at line 57 of file faceinvaderswidget.h.
Constructor & Destructor Documentation
FaceInvadersScene::FaceInvadersScene (QWidget * parent = 0) explicit
Default constructor.
Parameters
parent Sets the parent widget, See QT Docs
Definition at line 14 of file faceinvaderswidget.cpp.
References alienEvaded(), background, endGame(), m_advanceTimer, m_gameSize, m_playerStartingPosition, m_scoreItem, player, and updateScorePosition().
Member Function Documentation
void FaceInvadersScene::gameOver (int m_scoreItem) signal
Idicates game state transition to game over
Game over is defined as the player failure to avoid falling invaders or explicit call to FaceInvadersScene::endGame(). This signal is not emitted when the game is paused.
See Also
FaceInvadersScene::gamePaused()
Parameters
score The score of the game that just ended
void FaceInvadersScene::gamePaused () signal
Indiccates game state transition from playing to paused
The game has been explicitly paused by a call to FaceInvadersScene::pauseGame()
See Also
FaceInvadersScene::pauseGame()
void FaceInvadersScene::gameStarted (bool resumed) signal
Indicates game state transition from stopped to playing
Parameters
resumed Indicates if game was resumed, or fresh game was started
void FaceInvadersScene::setGameScreenSize (QRectF & rect)
Sets the rectangle for the game space.
Todo:
Make sure everything is updated and resized
Definition at line 60 of file faceinvaderswidget.cpp.
References m_gameSize, and updateScorePosition().
void FaceInvadersScene::setInvaderSpeed (qreal speed) slot
Set invader speed to specific value.
Todo:
explain invader speed value...
Parameters
speed ??
Definition at line 152 of file faceinvaderswidget.cpp.
The documentation for this class was generated from the following files:
src/faceinvaderswidget.h
src/faceinvaderswidget.cpp