Lockheed Inanimation: FaceInvadersWidget Class Reference
FaceInvadersWidget Class Reference
UI class for displaying the FaceInvaders game.
#include <faceinvaderswidget.h>
Public Slots
void beginGame ()
Calls FaceInvadersScene::beginGame()
void endGame ()
Calls FaceInvadersScene::endGame()
void initScreen ()
Shows a brief screen to acquire user image.
void pauseGame ()
Calls FaceInvadersScene::pauseGame()
void resetGame ()
Calls FaceInvadersScene::resetGame()
void updatePlayerImage (QImageSharedPointer image)
Sets the player image.
void updatePlayerPosition (QPoint position)
Calls FaceInvadersScene::updatePlayerPosition()
void updatePlayerPosition (QRect position)
Calls FaceInvadersScene::updatePlayerPosition()
Signals
void ceaseImageUpdates ()
Indicates that the class no longer wants to recieve updates for the player image.
void faceImageUpdatesRequest ()
Indicates that the class wants to recieve updates for the player iamge.
void gameOver (int score)
See FaceInvadersScene::gameOver()
void gamePaused ()
See FaceInvadersScene::gamePaused()
void gameStarted (bool resumed)
Indicates game state transition from stopped to playing
Public Member Functions
FaceInvadersWidget (QWidget *parent=0)
Constructor.
int heightForWidth (int w) const
Used to maintain aspect ratio of widget, See QT Docs
Static Public Attributes
static const int DefaultInitScreenTime = 10
static const int DefaultTimeBetweenGames = 10
Protected Slots
void initTimerExpired ()
Updates countdown for user face image acquisition.
void m_gameOver (int score)
Initializes countdown timer for new game.
void resetTimerExpired ()
Updates countdown for starting new game.
Protected Member Functions
void drawForeground (QPainter *painter, const QRectF &rect)
Displays Game Over message.
void resizeEvent (QResizeEvent *)
Used to maintain aspect ratio, See QT Docs
Private Attributes
bool m_initScreen
int m_initScreenCountDown
int m_initScreenSeconds
QTimer m_initTimer
QTimer m_restartTimer
FaceInvadersScene * m_scene
The game graphics scene.
int m_secondsBetweenGagmes
int m_secondsToRestart
Maintains count down for starting new game.
Detailed Description
UI class for displaying the FaceInvaders game.
This class can be used to display the FaceInvaders game to the user. The class provides similar signals and slots as the FaceInvadersScene class and behaves more or less as a shell around it. As it is only used for Displaying purposes, it does not contribute to the game logic.
Definition at line 204 of file faceinvaderswidget.h.
Constructor & Destructor Documentation
FaceInvadersWidget::FaceInvadersWidget (QWidget * parent = 0) explicit
Constructor.
Parameters
parent Sets the parent Widget, See QT Docs
Definition at line 209 of file faceinvaderswidget.cpp.
References gameOver(), gamePaused(), gameStarted(), initTimerExpired(), m_gameOver(), m_scene, and resetTimerExpired().
Member Function Documentation
void FaceInvadersWidget::drawForeground (QPainter * painter, const QRectF & rect) protected
Displays Game Over message.
Todo:
Use QSettings to store highest score
Definition at line 255 of file faceinvaderswidget.cpp.
References FaceInvadersScene::getGameScore(), FaceInvadersScene::getGameScreenSize(), FaceInvadersScene::getPlayerImage(), FaceInvadersScene::getState(), m_scene, and m_secondsToRestart.
void FaceInvadersWidget::gameStarted (bool resumed) signal
Indicates game state transition from stopped to playing
Parameters
resumed Indicates if game was resumed, or fresh game was started
void FaceInvadersWidget::initScreen () slot
Shows a brief screen to acquire user image.
This function emits RequestFaceImageUpdates, and expects the owner to supply images through the
Definition at line 411 of file faceinvaderswidget.cpp.
References faceImageUpdatesRequest(), m_scene, and FaceInvadersScene::resetGame().
The documentation for this class was generated from the following files:
src/faceinvaderswidget.h
src/faceinvaderswidget.cpp