.TH "MainWindow" 3 "Sun Feb 17 2013" "Lockheed Inanimation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::MainWindow * \fBui\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Lockheed Inanimation from the source code\&.
